n_epochs: 301
device: cuda:1
model_path: /home/alex/a.nevarko/models/efficientnet_b4_augs_224
exp_name: efficientnet_b4_augs_224

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-digits
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/balki/digits/train
    shuffle: True
    batch_size: 16
    num_workers: 1
    size: 224

val_data:
    root: /home/alex/a.nevarko/data/balki/digits/val
    shuffle: True
    batch_size: 16
    num_workers: 1
    size: 224

model:
    model: efficientnet_b4
    pretrained: True

optimizer:
    type: adam
    lr: 0.0003
    weight_decay: 0.0005
    lr_policy:
        type: multistep
        steps: [100, 200]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
