n_epochs: 101
device: cuda:1
model_path: /home/alex/a.nevarko/models/resnet34_augs_v3_digits_v3_128
exp_name: resnet34_augs_v3_digits_v3_128

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-digits
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/digits/digits_v2_balki/train
    weighted_sampling: False
    shuffle: True
    batch_size: 96
    num_workers: 0
    size: 128

val_data:
    root: /home/alex/a.nevarko/data/digits/digits_v2_balki/val
    weighted_sampling: False
    shuffle: True
    batch_size: 64
    num_workers: 0
    size: 128

model:
    model: resnet34
    pretrained: True

optimizer:
    type: adam
    lr: 0.0001
    weight_decay: 0.005
    lr_policy:
        type: multistep
        steps: [20, 50]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
