n_epochs: 301
device: cuda:0
model_path: /home/alex/a.nevarko/models/resnet34_sampling_augs_v3_digits_v2_224_pretrained
exp_name: resnet34_sampling_augs_v3_digits_v2_224_pretrained

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-digits
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/digits/digits_v2_balki/train
    weighted_sampling: True
    shuffle: True
    batch_size: 64
    num_workers: 0
    size: 224

val_data:
    root: /home/alex/a.nevarko/data/digits/digits_v2_balki/val
    weighted_sampling: True
    shuffle: True
    batch_size: 64
    num_workers: 0
    size: 224

model:
    model: resnet34
    pretrained: True
    checkpoint: /home/alex/a.nevarko/models/resnet34_sampling_augs_v1_digits_v1_224_pad/last.pth

optimizer:
    type: adam
    lr: 0.00003
    weight_decay: 0.001
    lr_policy:
        type: multistep
        steps: [50, 70]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
