n_epochs: 301
device: cuda:1
model_path: /home/alex/a.nevarko/models/vit_small_from_scratch
exp_name: vit_small_wd_from_scratch

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-digits
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/balki/digits/train
    shuffle: True
    batch_size: 64
    num_workers: 1

val_data:
    root: /home/alex/a.nevarko/data/balki/digits/val
    shuffle: True
    batch_size: 64
    num_workers: 1

model:
    model: vit_small_patch16_224_in21k
    pretrained: False

optimizer:
    type: adam
    lr: 0.0003
    weight_decay: 0.0001
    lr_policy:
        type: multistep
        steps: [20, 100]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
