device: cuda:0

model:
    model: efficientnet_b2
    pretrained: False
    checkpoint: /home/alex/a.nevarko/models/vagon_cls/efb2_augs_baseline_512/last.pth

inference_data:
    root: /home/alex/a.nevarko/data/gpt/vagons_cls/test_data/2023-01-27_11-12-49.217540/camera0_debug
    batch_size: 64
    num_workers: 0
    size: 512
    classes: {
        0: 'cisterna',
        1: 'fon',
        2: 'locomotiv',
        3: 'mezhvagon',
        4: 'par_cisterna',
        5: 'vagon',
    }
save_path: /home/alex/a.nevarko/data/gpt/vagons_cls/test_data/2023-01-27_11-12-49.217540_res


    
