device: cuda:0

model:
    model: mobilenetv3_large_100
    pretrained: False
    checkpoint: /home/alex/a.nevarko/models/vagon_cls/mobilenetv3_large_100_v2_balanced/last.pth

inference_data:
    root: /home/alex/a.nevarko/data/gpt/vagons_cls/test_data/2023-03-14_06-53-09.605540/R1_debug
    batch_size: 64
    num_workers: 2
    size: 512
    classes: {
        0: 'cisterna',
        1: 'fon',
        2: 'locomotiv',
        3: 'mezhvagon',
        4: 'par_cisterna',
        5: 'vagon',
    }
save_path: /home/alex/a.nevarko/data/gpt/vagons_cls/test_data/2023-03-14_06-53-09.605540_res/R1_debug


    
