n_epochs: 101
device: cuda:1
model_path: /home/alex/a.nevarko/models/rotator/efb2_ud_full512_ds_v4_crops
exp_name: efb2_ud_full512_ds_v4_crops

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-groups-rotate
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/balki/groups/upside_down_v4/train
    weighted_sampling: False
    shuffle: True
    batch_size: 8
    num_workers: 0
    size: 512

val_data:
    root: /home/alex/a.nevarko/data/balki/groups/upside_down_v4/val
    weighted_sampling: False
    shuffle: True
    batch_size: 2
    num_workers: 0
    size: 512

model:
    model: efficientnet_b2
    pretrained: True

optimizer:
    type: adam
    lr: 0.0003
    weight_decay: 0.001
    lr_policy:
        type: multistep
        steps: [20, 80]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
