n_epochs: 101
device: cuda:0
model_path: /home/alex/a.nevarko/models/rotator/mobilenetv3_large_100_full320_qu_v1_crops
exp_name: mobilenetv3_large_100_full320_qu_v1_crops

experiment:
    api_key: CfFmqDpTCtsdDkLooedZh7bs2
    project_name: Aurorai-balki-groups-rotate
    workspace: alexandernevarko
    auto_metric_logging: False

train_data:
    root: /home/alex/a.nevarko/data/balki/groups/qudrants_v1/train
    weighted_sampling: False
    shuffle: True
    batch_size: 32
    num_workers: 0
    size: 320

val_data:
    root: /home/alex/a.nevarko/data/balki/groups/qudrants_v1/test
    weighted_sampling: False
    shuffle: True
    batch_size: 32
    num_workers: 0
    size: 320

model:
    model: mobilenetv3_large_100
    pretrained: True

optimizer:
    type: adam
    lr: 0.0003
    weight_decay: 0.001
    lr_policy:
        type: multistep
        steps: [50, 80]
        gamma: 0.2

criterion:
    type: CrossEntropyLoss
    
